global:
  scrape_timeout: 10s
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka_controllers'
    static_configs:
      - targets:
          - 'controller-1:9401'
          - 'controller-2:9402'
          - 'controller-3:9403'
        labels:
          name: 'controller'
          role: 'controller'
          environment: 'local'

  - job_name: 'kafka_brokers'
    static_configs:
      - targets:
          - 'broker-1:9404'
          - 'broker-2:9405'
          - 'broker-3:9406'
        labels:
          name: 'broker'
          role: 'broker'
          environment: 'local'

  # Scrape Prometheus metrics (self-monitoring)
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'prometheus:9090'
        labels:
          name: 'prometheus'
          environment: 'local'

  # Scrape Grafana metrics
  - job_name: 'grafana'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'grafana:3000'
        labels:
          name: 'grafana'
          environment: 'local'
